<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="5" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="RegressionSuite" duration-ms="236395" started-at="2020-04-22T18:08:37 IST" finished-at="2020-04-22T18:12:34 IST">
    <groups>
    </groups>
    <test name="CompleteTest" duration-ms="236395" started-at="2020-04-22T18:08:37 IST" finished-at="2020-04-22T18:12:34 IST">
      <class name="com.mylearning.TestCases.LoginTest">
        <test-method status="PASS" signature="beforemethod()[pri:0, instance:com.mylearning.TestCases.LoginTest@306851c7]" name="beforemethod" is-config="true" duration-ms="49987" started-at="2020-04-22T18:08:37 IST" finished-at="2020-04-22T18:09:27 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforemethod -->
        <test-method status="PASS" signature="ValicadteWelcomeMsg()[pri:0, instance:com.mylearning.TestCases.LoginTest@306851c7]" name="ValicadteWelcomeMsg" duration-ms="1281" started-at="2020-04-22T18:09:27 IST" finished-at="2020-04-22T18:09:29 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValicadteWelcomeMsg -->
        <test-method status="PASS" signature="aftermethod()[pri:0, instance:com.mylearning.TestCases.LoginTest@306851c7]" name="aftermethod" is-config="true" duration-ms="1397" started-at="2020-04-22T18:09:33 IST" finished-at="2020-04-22T18:09:35 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftermethod -->
        <test-method status="PASS" signature="beforemethod()[pri:0, instance:com.mylearning.TestCases.LoginTest@306851c7]" name="beforemethod" is-config="true" duration-ms="30573" started-at="2020-04-22T18:09:35 IST" finished-at="2020-04-22T18:10:05 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforemethod -->
        <test-method status="PASS" signature="ValidateLogo()[pri:0, instance:com.mylearning.TestCases.LoginTest@306851c7]" name="ValidateLogo" duration-ms="476" started-at="2020-04-22T18:10:05 IST" finished-at="2020-04-22T18:10:06 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateLogo -->
        <test-method status="PASS" signature="aftermethod()[pri:0, instance:com.mylearning.TestCases.LoginTest@306851c7]" name="aftermethod" is-config="true" duration-ms="1342" started-at="2020-04-22T18:10:07 IST" finished-at="2020-04-22T18:10:09 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftermethod -->
        <test-method status="PASS" signature="beforemethod()[pri:0, instance:com.mylearning.TestCases.LoginTest@306851c7]" name="beforemethod" is-config="true" duration-ms="26180" started-at="2020-04-22T18:10:09 IST" finished-at="2020-04-22T18:10:35 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforemethod -->
        <test-method status="PASS" signature="checkbranch1()[pri:0, instance:com.mylearning.TestCases.LoginTest@306851c7]" name="checkbranch1" duration-ms="3" started-at="2020-04-22T18:10:35 IST" finished-at="2020-04-22T18:10:35 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkbranch1 -->
        <test-method status="PASS" signature="aftermethod()[pri:0, instance:com.mylearning.TestCases.LoginTest@306851c7]" name="aftermethod" is-config="true" duration-ms="1246" started-at="2020-04-22T18:11:03 IST" finished-at="2020-04-22T18:11:04 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftermethod -->
        <test-method status="PASS" signature="beforemethod()[pri:0, instance:com.mylearning.TestCases.LoginTest@306851c7]" name="beforemethod" is-config="true" duration-ms="30621" started-at="2020-04-22T18:11:04 IST" finished-at="2020-04-22T18:11:35 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforemethod -->
        <test-method status="FAIL" signature="testfail()[pri:0, instance:com.mylearning.TestCases.LoginTest@306851c7]" name="testfail" duration-ms="220" started-at="2020-04-22T18:11:35 IST" finished-at="2020-04-22T18:11:35 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:751)
at org.testng.Assert.assertEquals(Assert.java:761)
at com.mylearning.TestCases.LoginTest.testfail(LoginTest.java:72)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testfail -->
        <test-method status="PASS" signature="aftermethod()[pri:0, instance:com.mylearning.TestCases.LoginTest@306851c7]" name="aftermethod" is-config="true" duration-ms="1392" started-at="2020-04-22T18:11:38 IST" finished-at="2020-04-22T18:11:40 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftermethod -->
        <test-method status="PASS" signature="beforemethod()[pri:0, instance:com.mylearning.TestCases.LoginTest@306851c7]" name="beforemethod" is-config="true" duration-ms="26762" started-at="2020-04-22T18:11:40 IST" finished-at="2020-04-22T18:12:06 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforemethod -->
        <test-method status="FAIL" signature="validatelogin()[pri:0, instance:com.mylearning.TestCases.LoginTest@306851c7]" name="validatelogin" duration-ms="20818" started-at="2020-04-22T18:12:06 IST" finished-at="2020-04-22T18:12:27 IST">
          <exception class="java.lang.Error">
            <message>
              <![CDATA[Unresolved compilation problems: 
Unhandled exception type IOException
Unhandled exception type IOException
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Error: Unresolved compilation problems: 
Unhandled exception type IOException
Unhandled exception type IOException

at com.mylearning.TestCases.LoginTest.validatelogin(LoginTest.java:57)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Error -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validatelogin -->
        <test-method status="PASS" signature="aftermethod()[pri:0, instance:com.mylearning.TestCases.LoginTest@306851c7]" name="aftermethod" is-config="true" duration-ms="2028" started-at="2020-04-22T18:12:32 IST" finished-at="2020-04-22T18:12:34 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftermethod -->
      </class> <!-- com.mylearning.TestCases.LoginTest -->
    </test> <!-- CompleteTest -->
  </suite> <!-- RegressionSuite -->
</testng-results>
